### ISSUE TITLE
data grid header height

### ISSUE THREAD

**Issue by setin1219** [RicoSuter/MyToolkit#75]
Hi,

is there a way to increase datagrid header row height .

thanks,
nitesh

**Comment by jkronk** [comment]
You need to override the theme for the DataGrid. I ended up pulling in all of the resources and modifying them as necessary to achieve certain business rules. (Background colors, font colors, themes for rows all  dependent on certain criteria.)

**Comment by setin1219** [comment]
Hi Jkronk,

where can i find the resource file of toolkit.

thanks,
nitesh

**Comment by jkronk** [comment]
It is in the Themes in this GitHub directory.

**Comment by setin1219** [comment]
thanks, closing the ticket
